api = 1

[frames.forge-register]
page = "forge-register/index.html"
z = 200
focus = "input"
events_out = ["forge-register.*"]

[frames.bank]
page = "bank/index.html"
z = 200
focus = "input"
events_in = ["bank.*"]
events_out = ["bank.*"]